### PR TITLE
Added multiple instances feature

### PR DESCRIPTION
**Pull request by icaparros-at-wiris**
## Description

Added `Run several Moodle instances` feature: Now the user have the possibility to run two or more instances of moodle with different Moodle and PHP versions.

This task adds a new section on readme that document the process to run multiple moodle instances. The `.bin/wiris-moodle-docker-start` file was changed:

Added a prefix for the cookies name of the instance in order to use diferent cookies for each instance of moodle.
Changed logs to show the correct port used on each instance
Added a Change log file.

## Steps to reproduce
1. Open the terminal on the project.
2. Follow the steps from README:
2.1. Add advanced settings.
2.2. Install downloads all the necessary files and dependencies to your local computer (section 1 from readme).
2.3. Add the environment variable necessary to run a new instance of moodle (section 1.1 from readme).
2.4. Run the `wiris-moodle-docker-start` script to create the instance (section 2 from readme).
3. Repeat the second step with different versions of moodle and different container ports for each instance desired.
4. Access to each instance of Moodle with the url `localhost:<selected-port>`.
5. Log as admin in each (credentials on FAQ from readme).
6. Navigate to `Site administrator > Server > Session handling` and check if `Cookie prefix` is the same as the provided in the step 2.3.

### CODE REVIEW

**Review by dcanet-at-wiris — CHANGES_REQUESTED** [review]
Hi, @icaparros-at-wiris 

Here's my review for this PR.

First of all, congratulations for your work. This feature will be of enormous help to optimize our current software development cycle.

I'm asking you for review, since I've found an issue. At the same time, I'm adding some changes to the README file myself.

## Issue with multiple instances 

I've followed the instructions for the multiple instance configuration and everything seems to works fine. 

Unfortunately, I've found an issue when testing manually two Moodle instances that have been started simultaneously.

It seems there's a problem with the Cookie domain, and whenever I log in to a Moodle instance I am automatically logged out on the other active instance. 😢 

I'm adding a video:

https://user-images.githubusercontent.com/85346791/140039558-8baee9e8-5476-444e-b762-5aa888e6285c.mp4

> _For the record, I didn't download the Moodle core source code from scratch since it was already downloaded from previous wiris-moodle-docker installations. Should I had to remove the Moodle folders completely for the $cfg change to take effect?_

## Changes on the README file

I've decided to move down a bit the new section you've added to the README file: "Run several Moodle instances simultaneously". 

Now it has its own headline on the document. This way, it can be refered, as a link, from the FAQ secttion, too.

The reason is that since these instructions affect to both the "start" and "test" commands, I believe it's better to move it to a new section below, though

## Update the Changelog

Eventually, you could update the recently added CHANGES.md file with a new entry for this enhancement on multiple instances. 

I leave the decision up to you. But, since we agreed on #7 to use a changelog on this project, Imho, we should follow this new guideline.

What do you think?

**Comment by dcanet-at-wiris** [comment]
BTW, I'm adding @atomas-at-wiris to the pull request reviewers.

Since he is a known user of the tool, I think he will be interested on this enhancement.

**Comment by icaparros-at-wiris** [comment]
> ## Issue with multiple instances
> I've followed the instructions for the multiple instance configuration and everything seems to works fine.
> 
> Unfortunately, I've found an issue when testing manually two Moodle instances that have been started simultaneously.
> 
> It seems there's a problem with the Cookie domain, and whenever I log in to a Moodle instance I am automatically logged out on the other active instance. cry
> 
> I'm adding a video:
> 
>  wmd-session-error.mp4 

Hi, @dcanet-at-wiris the code added on `bin/wiris-moodle-docker-start` (75-81) should solve this issue, adding the selected name `COMPOSE_PROJECT_NAME` as a prefix for the cookies. Can you check If this prefix is added in each instance of moodle on `Site administration > Server > Session handling > Cookie prefix` (You must be logged as admin)?

Thank you!

image

**Comment by icaparros-at-wiris** [comment]
## Updated the multiple instances feature.
When the user wants to run several instance with different versions of moodle at the same time, have to set the `WIRIS_MOODLE_MULTIPLE='on'`.
`COMPOSE_PROJECT_NAME` is the environment variable used to name each moodle instance. The differents scripts will set the `COMPOSE_PROJECT_NAME` equal to `WIRIS_MOODLE_BRANCH` so the user will only have to modify one environment variable to use the scripts in a specific instance.
Added scripts to run behat and php test, to set the `COMPOSE_PROJECT_NAME` automatically if the multipe instance flag is enable:
```
# Example: Run some behat tests by tag.
$ ./bin/wiris-moodle-docker-test-behat -t filter_wiris
# Example: Run a phpunit tests
$ ./bin/wiris-moodle-docker-test-php -t manual_test.php
```

**Comment by icaparros-at-wiris** [comment]
## Updated the multiple instances feature.
When the user wants to run several instance with different versions of moodle at the same time, have to set the `WIRIS_MOODLE_MULTIPLE='on'`.

`COMPOSE_PROJECT_NAME` is the environment variable used to name each moodle instance. The differents scripts will set the `COMPOSE_PROJECT_NAME` equal to `WIRIS_MOODLE_BRANCH` so the user will only have to modify one environment variable to use the scripts in a specific instance.

Added scripts to run behat and php test, to set the `COMPOSE_PROJECT_NAME` automatically if the multipe instance flag is enable:
```
# Example: Run some behat tests by tag.
$ ./bin/wiris-moodle-docker-test-behat -t filter_wiris
# Example: Run a phpunit tests
$ ./bin/wiris-moodle-docker-test-php -t manual_test.php
```

**Review by xripoll-at-wiris — APPROVED** [review]

**Review by carla-at-wiris — APPROVED** [review]

**Review by dcanet-at-wiris — CHANGES_REQUESTED** [review]
Awesome work, Isaac!

I hope you don't mind but I am requesting changes on this. 🙈 

## How the HTTP port number is calculated on multiple instance mode?

I am missing some kind of explanation on the documentation about how the port number/s is/are calculated on the multiple instance mode. Plural, because If I am not wrong, the VNC server HTTP port would need to be defined for each started instance, too. 

The `start` command message includes the PORT number used as a link to the Moodle instance. Kudos for that, Isaac!

But I believe this is not enough.

```bash
===============================================================================================
=> Build is finished. Visit your MOODLE_311_STABLE (PHP_7.4) Instance at http://localhost:10311/.
===============================================================================================
```
Imho this could be troublesome for the user if they don't pay attention to this message, or if it's their first time using the multiple-instance new feature.

You could consider if it works fine as new entry on th FAQ section.

**Pull request merged**
